apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KaW5oaWJpdF9ydWxlczoKLSBlcXVhbDoKICAtIG5hbWVzcGFjZQogIC0gYWxlcnRuYW1lCiAgc291cmNlX21hdGNoZXJzOgogIC0gc2V2ZXJpdHkgPSBjcml0aWNhbAogIHRhcmdldF9tYXRjaGVyczoKICAtIHNldmVyaXR5ID1+IHdhcm5pbmd8aW5mbwotIGVxdWFsOgogIC0gbmFtZXNwYWNlCiAgLSBhbGVydG5hbWUKICBzb3VyY2VfbWF0Y2hlcnM6CiAgLSBzZXZlcml0eSA9IHdhcm5pbmcKICB0YXJnZXRfbWF0Y2hlcnM6CiAgLSBzZXZlcml0eSA9IGluZm8KLSBlcXVhbDoKICAtIG5hbWVzcGFjZQogIHNvdXJjZV9tYXRjaGVyczoKICAtIGFsZXJ0bmFtZSA9IEluZm9JbmhpYml0b3IKICB0YXJnZXRfbWF0Y2hlcnM6CiAgLSBzZXZlcml0eSA9IGluZm8KLSB0YXJnZXRfbWF0Y2hlcnM6CiAgLSBhbGVydG5hbWUgPSBJbmZvSW5oaWJpdG9yCnJlY2VpdmVyczoKLSBuYW1lOiAic2xhY2stYWxlcnRzIiAgICAgICAjIOKchSByZXBsYWNlZCAibnVsbCIKICBzbGFja19jb25maWdzOgogIC0gYXBpX3VybDogImh0dHBzOi8vaG9va3Muc2xhY2suY29tL3NlcnZpY2VzL1QwQVJXMFlSTVY1L0IwQVJYQjBTQjFEL21wWkI3aE02R1R4QktsOEtNU0Fub08xaCIKICAgIGNoYW5uZWw6ICIjYWxlcnRzIgogICAgc2VuZF9yZXNvbHZlZDogdHJ1ZQpyb3V0ZToKICByZWNlaXZlcjogInNsYWNrLWFsZXJ0cyIgICAjIOKchSBjaGFuZ2VkIGZyb20gIm51bGwiCiAgZ3JvdXBfYnk6CiAgICAtIG5hbWVzcGFjZQogIGdyb3VwX3dhaXQ6IDMwcwogIGdyb3VwX2ludGVydmFsOiA1bQogIHJlcGVhdF9pbnRlcnZhbDogMTJoCgp0ZW1wbGF0ZXM6Ci0gL2V0Yy9hbGVydG1hbmFnZXIvY29uZmlnLyoudG1wbA== 
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2026-04-11T08:32:50Z"
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 83.4.0
    chart: kube-prometheus-stack-83.4.0
    heritage: Helm
    release: kube-prometheus-stack
  name: alertmanager-kube-prometheus-stack-alertmanager
  namespace: monitoring
  resourceVersion: "60784"
  uid: d205c658-c94b-4e96-8153-5c6f41d02abf
type: Opaque
