apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-service-monitor
  labels:
    release: kube-prometheus-stack 
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
  - port: metrics
    interval: 15s 
    path: /metrics
  namespaceSelector:
    matchNames:
    - default

    